# Generated by Django 5.0.14 on 2025-08-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_project_image_remove_project_live_url_and_more'),
    ]

    operations = [
    ]
